<?php

namespace AppBundle\Repository;

/**
 * documentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
