<?php

namespace AppBundle\Repository;

/**
 * trabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
